SHEET_ID = "ID_SHEET_ANDA"
SHEET_NAME = "Sheet1"
INSTANSI = "BPKPD KAB.HST"
JUDUL_SITUS = "Pusat Unduhan Berkas REKON BMD 2026"
SUBJUDUL = "Unduh dokumen, format, dan formulir resmi dengan mudah dan cepat."
LOGO_URL = "https://upload.wikimedia.org/wikipedia/commons/6/65/Lambang_Kabupaten_Hulu_Sungai_Tengah.png?utm_source=id.wikipedia.org&utm_campaign=index&utm_content=original"
KONTAK = "bpkadhst.bidangaset@gmail.com"
